/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package belajar.gradle;

import com.sun.deploy.util.StringUtils;

public class Library {
    public static  void main(String[] args) {
        String nama = StringUtils.replaceSeparators(String.join("", args));
        System.out.println(nama);

    }

}





